#Docker-compose configurações, comentado porque estou com o arquivo do  docker compose fora da pasta code-challenge-swat

#version: '3.9'
#services:
#  db:
#    image: postgres:16.1
#    environment:
#      POSTGRES_DB: api_restfull_code_challenge
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres1234
#    ports:
#      - "5432:5432"
#    networks:
#      - maaicondgl-network
#    restart: always
#
#  api-restfull-code-challenge:
#    image: maaicondgl/code-challenge-swat
#    restart: always
#    build: ./code-challenge-swat
#    environment:
#      TZ: America/Sao_Paulo
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/api_restfull_code_challenge
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres1234
#    ports:
#      - "8080:8080"
#    command: mvn spring-boot:run
#    networks:
#      - maaicondgl-network
#
#networks:
#  maaicondgl-network:
#    driver: bridge