version: '3.9'
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: api_restfull_code_challenge
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    command: postgres --default-authentication-plugin=postgres_native_password
    networks:
      - maaicondgl-network
    restart: always
  api-restfull-code-challenge:
    image: maaicondgl/code-challenge-swat
    restart: always
    build: ./code-challenge-swat
    working_dir: /code-challenge-swat
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/api_restfull_code_challenge
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres1234
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
networks:
  maaicondgl-network:
    driver: bridge